artifact_location: file:///C:/Users/luism/OneDrive/Ambiente de Trabalho/EI/3ยบ ANO/2ยบ
  SEMESTRE/AOP/Computer_Vision/ASL/runs/mlflow/0
creation_time: 1749235885950
experiment_id: '0'
last_update_time: 1749235885950
lifecycle_stage: active
name: Default
